#ifndef YASEMQMLGUI_GLOBAL_H
#define YASEMQMLGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(YASEMQMLGUI_LIBRARY)
#  define YASEMQMLGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define YASEMQMLGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // YASEMQMLGUI_GLOBAL_H
